import type { Metadata } from "next";
import { Padauk } from "next/font/google";
import "./globals.css";

const padauk = Padauk({
  subsets: ["myanmar", "latin"],
  weight: ["400", "700"],
  variable: "--font-padauk",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="my" className={`${padauk.variable} h-full antialiased`}>
      <body className={`${padauk.className} min-h-full flex flex-col bg-gray-50`}>
        {children}
      </body>
    </html>
  );
}
